steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.billing-aggregator'
      - '-t'
      - 'us-central1-docker.pkg.dev/salucainfrastructure/tiresias/tiresias-billing-aggregator:v0.1.4'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/salucainfrastructure/tiresias/tiresias-billing-aggregator:v0.1.4'
