steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-f','Dockerfile.proxy','-t','us-central1-docker.pkg.dev/salucainfrastructure/tiresias/tiresias-proxy:v0.6.15','.']
images: ['us-central1-docker.pkg.dev/salucainfrastructure/tiresias/tiresias-proxy:v0.6.15']
