/**
 * Business OS Phase 5 — expense report PDF template.
 *
 * Renders an expense list table with date, category, vendor, description,
 * and amount columns, plus category-level subtotals.
 *
 * @license MIT — Tiresias Business OS Phase 5 (internal).
 */

import React from 'react';
import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@/lib/agentic-os/_shared/pdf/primitives';
import {
  PdfPageStyles,
  PdfHeader,
  PdfFooter,
  PdfMetadataBlock,
  PdfTable,
} from '@/lib/agentic-os/_shared/pdf/primitives';
import type { Expense, ExpenseCategory } from '../expenses';

const styles = StyleSheet.create({
  ...PdfPageStyles,
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginTop: 14,
    marginBottom: 6,
    color: '#0f172a',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingVertical: 4,
    borderTopWidth: 1,
    borderTopColor: '#0f172a',
    marginTop: 6,
  },
  totalLabel: {
    fontSize: 10,
    fontWeight: 700,
    marginRight: 16,
    color: '#0f172a',
  },
  totalValue: {
    fontSize: 10,
    fontWeight: 700,
    color: '#0f172a',
    width: 100,
    textAlign: 'right',
  },
  categoryTotalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingVertical: 2,
    marginTop: 2,
  },
  categoryTotalLabel: {
    fontSize: 8,
    color: '#475569',
    marginRight: 16,
  },
  categoryTotalValue: {
    fontSize: 8,
    fontWeight: 700,
    color: '#475569',
    width: 100,
    textAlign: 'right',
  },
});

function fmtCents(cents: number, currency: string): string {
  const val = (Math.abs(cents) / 100).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return (cents < 0 ? '-' : '') + currency + ' ' + val;
}

interface ExpenseReportPdfProps {
  expenses: Expense[];
  periodStart?: string;
  periodEnd?: string;
  title?: string;
}

export function ExpenseReportDocument({
  expenses,
  periodStart,
  periodEnd,
  title,
}: ExpenseReportPdfProps) {
  const reportTitle = title || 'Expense Report';
  const subtitle = periodStart && periodEnd
    ? `${periodStart} to ${periodEnd}`
    : null;

  // Compute category totals
  const catTotals = new Map<ExpenseCategory, number>();
  let grandTotal = 0;
  let primaryCurrency = 'USD';
  for (const e of expenses) {
    grandTotal += e.amountCents;
    primaryCurrency = e.currency || primaryCurrency;
    catTotals.set(e.category, (catTotals.get(e.category) ?? 0) + e.amountCents);
  }

  const fields = [
    { label: 'Total Expenses', value: fmtCents(grandTotal, primaryCurrency) },
    { label: 'Entries', value: String(expenses.length) },
    { label: 'Currency', value: primaryCurrency },
    ...(periodStart ? [{ label: 'Period Start', value: periodStart }] : []),
    ...(periodEnd ? [{ label: 'Period End', value: periodEnd }] : []),
  ];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PdfHeader
          title={reportTitle}
          subtitle={subtitle}
        />
        <PdfFooter />

        <PdfMetadataBlock fields={fields} />

        {/* Expense table */}
        <PdfTable
          columns={[
            { header: 'Date', width: 1.5, render: (r: Expense) => r.incurredOn },
            { header: 'Category', width: 2, render: (r: Expense) => r.category },
            { header: 'Vendor', width: 2, render: (r: Expense) => r.vendor ?? '' },
            { header: 'Description', width: 3.5, render: (r: Expense) => r.description },
            { header: 'Amount', width: 2, render: (r: Expense) => fmtCents(r.amountCents, r.currency) },
          ]}
          rows={expenses}
        />

        {/* Category subtotals */}
        <Text style={styles.sectionTitle}>Category Subtotals</Text>
        {[...catTotals.entries()]
          .sort(([, a], [, b]) => b - a)
          .map(([cat, total]) => (
            <View key={cat} style={styles.categoryTotalRow}>
              <Text style={styles.categoryTotalLabel}>{cat}</Text>
              <Text style={styles.categoryTotalValue}>{fmtCents(total, primaryCurrency)}</Text>
            </View>
          ))}

        {/* Grand total */}
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total</Text>
          <Text style={styles.totalValue}>{fmtCents(grandTotal, primaryCurrency)}</Text>
        </View>

        <Text style={{ marginTop: 24, fontSize: 8, color: '#94a3b8', textAlign: 'center' }}>
          Generated by Pantheon Business OS
        </Text>
      </Page>
    </Document>
  );
}
