apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: soulgate-backendconfig
  namespace: tiresias
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8002
    type: HTTP
    requestPath: /gate/health
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: soulwatch-backendconfig
  namespace: tiresias
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8001
    type: HTTP
    requestPath: /watch/health
