"""LLM available-models registry — populated by the 6h cloud-LLM heartbeat.

Revision ID: 0071_llm_available_models
Revises: 0070_shared_saved_views
Create Date: 2026-05-18

Pantheon stopped local Ollama and committed to cloud LLM providers
(Anthropic, OpenRouter, Gemini, Ollama Cloud). To track which models are
currently offered, a CronJob polls each provider's /models endpoint every
6 hours and upserts here. Callers (model picker UI, agent config, coach
selection) query this table to get a fresh list without making N synchronous
upstream calls per page load.

Schema delta
------------

1. ``_llm_available_models`` (NEW — one row per provider+model pair)
     - ``id UUID PK`` — generated by the heartbeat worker.
     - ``provider TEXT NOT NULL`` — stable provider key. Current values:
       ``anthropic``, ``openrouter``, ``gemini``, ``ollama_cloud``. New
       providers can be added without migration; this is a free-form
       enum at the application layer.
     - ``model_id TEXT NOT NULL`` — provider-native model identifier
       (e.g. ``claude-sonnet-4-6``, ``anthropic/claude-haiku``,
       ``gemini-2.5-flash``, ``llama3.3:70b``).
     - ``display_name TEXT NULL`` — human-readable name from provider.
       Optional because some providers don't return one.
     - ``context_window INT NULL`` — token capacity. NULL when provider
       doesn't disclose.
     - ``max_output_tokens INT NULL`` — completion token cap. NULL when
       provider doesn't disclose.
     - ``capabilities JSONB NOT NULL DEFAULT '{}'`` — feature flags:
       ``{vision: true, tool_use: true, json_mode: true, streaming: true}``.
       Free-form; the heartbeat normalizes per-provider quirks into a
       common shape but extra keys are allowed.
     - ``pricing JSONB NOT NULL DEFAULT '{}'`` — provider-stated cost,
       canonicalized: ``{input_per_1m_usd: 3.0, output_per_1m_usd: 15.0,
       currency: "USD"}``. NULL fields when provider doesn't disclose
       (e.g. some OpenRouter community models).
     - ``first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()`` — when this
       row was first inserted. Useful for "new model" detection in UI.
     - ``last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()`` — most recent
       heartbeat poll that saw this model. The heartbeat updates this on
       every successful poll.
     - ``deprecated_at TIMESTAMPTZ NULL`` — set when the heartbeat fails
       to see the model in 2+ consecutive polls (i.e. provider removed
       it). The row is kept (audit history) but UI dims/hides it.
     - ``metadata JSONB NOT NULL DEFAULT '{}'`` — raw per-provider blob
       (release notes, training cutoff, modalities, anything the provider
       returns that doesn't fit the canonical columns).

Locked design decisions
-----------------------
- **No FK on ``provider``.** Free-form enum at the app layer. Adding a
  CHECK would force a migration every time a new provider is added.
- **Hard upsert by (provider, model_id).** Each poll either inserts or
  updates the existing row (bumps ``last_seen_at``, clears ``deprecated_at``).
- **Soft deprecation.** Rows are never deleted by the heartbeat — only
  ``deprecated_at`` is set. Lets us show "previously available" models.
- **No tenant scoping.** Model availability is global. Per-tenant
  routing/restrictions live in a separate table (future work).

Idempotency
-----------
CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS guards re-application.

License note: All DDL is original work under MIT.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "0071_llm_available_models"
down_revision: Union[str, None] = "0070_shared_saved_views"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_UPGRADE_SQL = r"""
-- LLM available-models registry — populated by the 6h heartbeat CronJob.

CREATE TABLE IF NOT EXISTS _llm_available_models (
    id                 UUID PRIMARY KEY,
    provider           TEXT NOT NULL,
    model_id           TEXT NOT NULL,
    display_name       TEXT,
    context_window     INT,
    max_output_tokens  INT,
    capabilities       JSONB NOT NULL DEFAULT '{}'::jsonb,
    pricing            JSONB NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deprecated_at      TIMESTAMPTZ,
    metadata           JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT _llm_available_models_provider_model_unique
        UNIQUE (provider, model_id)
);

COMMENT ON TABLE _llm_available_models IS
  'Cloud-LLM model availability registry, refreshed every 6h by a CronJob polling provider /models endpoints. Source of truth for model pickers, agent config, coach selection. Models removed from a provider have deprecated_at set but the row is retained for audit.';

COMMENT ON COLUMN _llm_available_models.provider IS
  'Stable provider key. Current values: anthropic, openrouter, gemini, ollama_cloud. Free-form at app layer (no CHECK) so new providers can be added without migration.';

COMMENT ON COLUMN _llm_available_models.capabilities IS
  'Normalized feature flags: vision, tool_use, json_mode, streaming. Extra keys allowed for provider-specific features.';

COMMENT ON COLUMN _llm_available_models.pricing IS
  'Canonical: {input_per_1m_usd, output_per_1m_usd, currency}. Some providers do not disclose pricing (e.g. OpenRouter community models) — those keys are absent.';

COMMENT ON COLUMN _llm_available_models.deprecated_at IS
  'Set when 2+ consecutive heartbeat polls fail to see this model in the provider response. Row is retained for audit; UI dims/hides deprecated rows.';

-- Index for "list models for one provider, freshest first"
CREATE INDEX IF NOT EXISTS _llm_available_models_provider_last_seen_idx
    ON _llm_available_models (provider, last_seen_at DESC);

-- Partial index for "list currently-available models only" (most common UI query)
CREATE INDEX IF NOT EXISTS _llm_available_models_active_idx
    ON _llm_available_models (provider, model_id)
    WHERE deprecated_at IS NULL;
"""


_DOWNGRADE_SQL = r"""
-- Reverse of UPGRADE in dependency order (indexes before table).

DROP INDEX IF EXISTS _llm_available_models_active_idx;
DROP INDEX IF EXISTS _llm_available_models_provider_last_seen_idx;

DROP TABLE IF EXISTS _llm_available_models;
"""


def upgrade() -> None:
    op.execute(_UPGRADE_SQL)


def downgrade() -> None:
    op.execute(_DOWNGRADE_SQL)
