/**
 * Autobiographer OS — Book Export PDF template.
 *
 * Renders a full book: title-page meta, then each chapter's latest
 * revision body with paragraph-level footnotes, then a provenance
 * appendix listing every cited memory with the chapters that cite it.
 *
 * Phase 5 seam — the chapter loop iterates whatever ordering the route
 * passes in. Phase 4 routes default to `position`; Phase 5 will compute
 * an arc-ordered chapter id list and pass it instead. The function
 * signature stays the same.
 *
 * @license MIT — Tiresias Autobiographer OS Phase 4 (internal).
 */

import * as React from 'react';
import {
  Document,
  Page,
  View,
  Text,
  PdfHeader,
  PdfFooter,
  PdfMetadataBlock,
  PdfPageStyles,
  StyleSheet,
} from '../../_shared/pdf/primitives';
import {
  CHAPTER_STATUS_LABELS,
  type ChapterStatus,
} from '../chapters';
import { splitParagraphs } from './chapter-export';
import type { RevisionCitation } from '../chapter-revisions';

const FOOTER_TEXT =
  'Generated by Pantheon Autobiographer OS — provenance preserved';

export interface BookPdfBook {
  title: string;
  subtitle?: string | null;
  description?: string | null;
  status: string;
  targetCompletionDate?: string | null;
  targetAudience?: string | null;
}

export interface BookPdfChapter {
  id: string;
  title: string | null;
  slug: string | null;
  position: number;
  status: ChapterStatus;
  summary: string | null;
  /** Latest revision attached to this chapter, or null if no revisions. */
  latest: {
    version: number;
    author: 'user' | 'coach';
    bodyText: string;
    wordCount: number;
    citations: RevisionCitation[];
  } | null;
}

export interface BookPdfMemoryLookup {
  id: string;
  title: string | null;
  whenInLife: string | null;
}

export interface BookPdfProvenanceRow {
  memoryId: string;
  memoryTitle: string;
  memoryWhenInLife: string | null;
  chapterReferences: Array<{
    chapterId: string;
    chapterTitle: string | null;
    chapterSlug: string | null;
    position: number;
  }>;
}

export interface BookExportPdfProps {
  book: BookPdfBook;
  authorName?: string | null;
  chapters: BookPdfChapter[];
  memories: BookPdfMemoryLookup[];
  provenance: BookPdfProvenanceRow[];
  generatedAt?: Date;
}

const styles = StyleSheet.create({
  titleH1: {
    fontSize: 26,
    fontWeight: 700,
    marginBottom: 6,
    color: '#0f172a',
  },
  titleSub: {
    fontSize: 13,
    color: '#475569',
    marginBottom: 18,
  },
  description: {
    fontSize: 10.5,
    color: '#0f172a',
    lineHeight: 1.5,
    marginBottom: 14,
  },
  chapterH2: {
    fontSize: 16,
    fontWeight: 700,
    marginTop: 6,
    marginBottom: 4,
    color: '#0f172a',
  },
  chapterMeta: {
    fontSize: 9,
    color: '#475569',
    marginBottom: 8,
  },
  statusBadge: {
    fontSize: 8,
    color: '#0f172a',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: '#0f172a',
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 6,
  },
  summary: {
    fontSize: 9.5,
    color: '#0f172a',
    backgroundColor: '#f1f5f9',
    padding: 6,
    borderLeftWidth: 2,
    borderLeftColor: '#0f172a',
    marginBottom: 10,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.55,
    marginBottom: 8,
    color: '#0f172a',
  },
  footnote: {
    fontSize: 8,
    color: '#475569',
    marginBottom: 2,
  },
  empty: {
    fontSize: 10,
    color: '#475569',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  appendixHeading: {
    fontSize: 14,
    fontWeight: 700,
    marginTop: 4,
    marginBottom: 6,
    color: '#0f172a',
  },
  appendixRow: {
    fontSize: 9,
    color: '#0f172a',
    marginBottom: 4,
    lineHeight: 1.4,
  },
});

function shortMemoryId(memoryId: string): string {
  const tidy = memoryId.replace(/-/g, '');
  return `M-${tidy.slice(0, 6)}`;
}

function superscript(n: number): string {
  if (n < 1) return '';
  const map: Record<number, string> = {
    1: '¹',
    2: '²',
    3: '³',
    4: '⁴',
    5: '⁵',
    6: '⁶',
    7: '⁷',
    8: '⁸',
    9: '⁹',
  };
  return map[n] ?? `[${n}]`;
}

export function BookExportPdf({
  book,
  authorName,
  chapters,
  memories,
  provenance,
  generatedAt,
}: BookExportPdfProps): React.ReactElement {
  const memoryById = new Map<string, BookPdfMemoryLookup>();
  for (const m of memories) memoryById.set(m.id, m);

  // Title page word count = sum of latest-revision word counts.
  const totalWords = chapters.reduce(
    (acc, c) => acc + (c.latest?.wordCount ?? 0),
    0,
  );

  const titleMeta = [
    { label: 'Status', value: book.status },
    { label: 'Chapters', value: String(chapters.length) },
    { label: 'Word count', value: totalWords.toLocaleString() },
    {
      label: 'Audience',
      value: book.targetAudience ?? '—',
    },
    {
      label: 'Target',
      value: book.targetCompletionDate ?? '—',
    },
    {
      label: 'Author',
      value: authorName ?? '—',
    },
  ];

  return (
    <Document>
      {/* ─── Title page ───────────────────────────────────────── */}
      <Page size="LETTER" style={PdfPageStyles.page}>
        <PdfHeader
          title="Book export"
          subtitle="Pantheon Autobiographer OS"
          generatedAt={generatedAt}
        />
        <Text style={styles.titleH1}>{book.title}</Text>
        {book.subtitle ? (
          <Text style={styles.titleSub}>{book.subtitle}</Text>
        ) : null}
        {book.description ? (
          <Text style={styles.description}>{book.description}</Text>
        ) : null}
        <PdfMetadataBlock fields={titleMeta} />
        <PdfFooter projectName={FOOTER_TEXT} />
      </Page>

      {/* ─── Chapters ─────────────────────────────────────────── */}
      {chapters.map((chapter) => {
        const latest = chapter.latest;
        const paragraphs = latest ? splitParagraphs(latest.bodyText) : [];
        const citations = latest?.citations ?? [];
        const citationsByParagraph = new Map<number, RevisionCitation>();
        for (const c of citations) citationsByParagraph.set(c.paragraphIndex, c);

        // Per-chapter footnote ordering — restart at each chapter so
        // the markers in the body align with the per-chapter footnote
        // list at the bottom of the chapter page.
        const footnoteOrder: string[] = [];
        const footnoteIndex = new Map<string, number>();
        for (const c of citations) {
          for (const memoryId of c.memoryIds) {
            if (!footnoteIndex.has(memoryId)) {
              footnoteOrder.push(memoryId);
              footnoteIndex.set(memoryId, footnoteOrder.length);
            }
          }
        }

        const chapterTitle = chapter.title ?? 'Untitled chapter';
        const positionLabel = `Ch ${String(chapter.position + 1).padStart(2, '0')}`;
        return (
          <Page
            key={`chapter-${chapter.id}`}
            size="LETTER"
            style={PdfPageStyles.page}
          >
            <PdfHeader
              title={chapterTitle}
              subtitle={`${book.title} — ${positionLabel}`}
              projectName="Pantheon Autobiographer OS"
              generatedAt={generatedAt}
            />

            <View
              style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 4 }}
            >
              <Text style={styles.chapterMeta}>
                {latest
                  ? `Revision v${latest.version} by ${
                      latest.author === 'coach' ? 'coach' : 'user'
                    } · ${latest.wordCount.toLocaleString()} words · ${paragraphs.length} ${paragraphs.length === 1 ? 'paragraph' : 'paragraphs'}`
                  : 'No revisions yet'}
              </Text>
              <Text style={styles.statusBadge}>
                {CHAPTER_STATUS_LABELS[chapter.status]}
              </Text>
            </View>

            {chapter.summary ? (
              <Text style={styles.summary}>{chapter.summary}</Text>
            ) : null}

            {paragraphs.length === 0 ? (
              <Text style={styles.empty}>
                This chapter has no prose yet.
              </Text>
            ) : (
              paragraphs.map((p, i) => {
                const cite = citationsByParagraph.get(i);
                const markers = cite
                  ? cite.memoryIds
                      .map((mid) => footnoteIndex.get(mid))
                      .filter((n): n is number => typeof n === 'number')
                      .map((n) => superscript(n))
                      .join('')
                  : '';
                return (
                  <Text key={`p-${chapter.id}-${i}`} style={styles.paragraph}>
                    {p}
                    {markers ? ' ' : ''}
                    {markers}
                  </Text>
                );
              })
            )}

            {footnoteOrder.length > 0 ? (
              <View wrap={false}>
                <Text
                  style={{
                    fontSize: 8,
                    color: '#475569',
                    textTransform: 'uppercase',
                    marginTop: 12,
                    marginBottom: 4,
                  }}
                >
                  Source memories
                </Text>
                {footnoteOrder.map((mid, i) => {
                  const memory = memoryById.get(mid);
                  const title = memory?.title ?? 'memory not available';
                  const era = memory?.whenInLife ? ` (${memory.whenInLife})` : '';
                  return (
                    <Text key={`fn-${chapter.id}-${mid}`} style={styles.footnote}>
                      {superscript(i + 1)} from memory {shortMemoryId(mid)} ‘{title}’
                      {era}
                    </Text>
                  );
                })}
              </View>
            ) : null}

            <PdfFooter projectName={FOOTER_TEXT} />
          </Page>
        );
      })}

      {/* ─── Provenance appendix ─────────────────────────────── */}
      <Page size="LETTER" style={PdfPageStyles.page}>
        <PdfHeader
          title="Provenance appendix"
          subtitle={book.title}
          projectName="Pantheon Autobiographer OS"
          generatedAt={generatedAt}
        />
        <Text style={styles.appendixHeading}>Cited memories</Text>
        {provenance.length === 0 ? (
          <Text style={styles.empty}>No memories cited yet.</Text>
        ) : (
          provenance.map((row) => {
            const refs = row.chapterReferences
              .map((c) => {
                const label = c.chapterTitle ?? c.chapterSlug ?? `chapter-${c.position + 1}`;
                return `Ch ${String(c.position + 1).padStart(2, '0')} ‘${label}’`;
              })
              .join(', ');
            const era = row.memoryWhenInLife ? ` (${row.memoryWhenInLife})` : '';
            return (
              <Text key={`prov-${row.memoryId}`} style={styles.appendixRow}>
                {shortMemoryId(row.memoryId)} ‘{row.memoryTitle}’{era} → {refs}
              </Text>
            );
          })
        )}
        <PdfFooter projectName={FOOTER_TEXT} />
      </Page>
    </Document>
  );
}
