/**
 * Autobiographer OS — Chapter Export PDF template.
 *
 * Renders one chapter revision as a self-contained PDF using the
 * OS-agnostic `_shared/pdf` primitives. The body paragraphs are
 * footnoted from the revision's `citations` payload — every
 * paragraph that carries a citation entry gets a superscript marker
 * and an end-of-page footnote anchoring back to the source memory.
 *
 * Footer (per page): "Generated by Pantheon Autobiographer OS —
 * provenance preserved" (set as the `projectName` arg to PdfFooter so
 * the shared primitive renders the existing footer slot without a new
 * variant).
 *
 * @license MIT — Tiresias Autobiographer OS Phase 4 (internal).
 */

import * as React from 'react';
import {
  Document,
  Page,
  View,
  Text,
  PdfHeader,
  PdfFooter,
  PdfPageStyles,
  StyleSheet,
} from '../../_shared/pdf/primitives';
import {
  CHAPTER_STATUS_LABELS,
  type ChapterStatus,
} from '../chapters';
import type { RevisionCitation } from '../chapter-revisions';

/** Minimal book shape consumed by the chapter PDF. */
export interface ChapterPdfBook {
  title: string;
  subtitle?: string | null;
}

/** Minimal chapter shape consumed by the chapter PDF. */
export interface ChapterPdfChapter {
  title: string | null;
  slug: string | null;
  position: number;
  status: ChapterStatus;
  summary: string | null;
}

/** Minimal revision shape consumed by the chapter PDF. */
export interface ChapterPdfRevision {
  version: number;
  author: 'user' | 'coach';
  bodyText: string;
  wordCount: number;
  citations: RevisionCitation[];
  createdAt: string;
}

/**
 * Lookup row for footnote rendering. Keyed by memory id; the route
 * loads the user's memories for every cited id and passes the index
 * here.
 */
export interface ChapterPdfMemoryLookup {
  id: string;
  title: string | null;
  whenInLife: string | null;
}

const styles = StyleSheet.create({
  statusBadge: {
    fontSize: 8,
    color: '#0f172a',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: '#0f172a',
    borderRadius: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 6,
  },
  meta: {
    fontSize: 9,
    color: '#475569',
    marginBottom: 8,
  },
  summary: {
    fontSize: 9.5,
    color: '#0f172a',
    backgroundColor: '#f1f5f9',
    padding: 6,
    borderLeftWidth: 2,
    borderLeftColor: '#0f172a',
    marginBottom: 10,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.55,
    marginBottom: 8,
    color: '#0f172a',
  },
  footnoteHeading: {
    fontSize: 8,
    color: '#475569',
    textTransform: 'uppercase',
    marginTop: 12,
    marginBottom: 4,
  },
  footnote: {
    fontSize: 8,
    color: '#475569',
    marginBottom: 2,
  },
  empty: {
    fontSize: 10,
    color: '#475569',
    fontStyle: 'italic',
  },
});

/** Stable short id for footnote markers (`M-<6 chars>`). */
function shortMemoryId(memoryId: string): string {
  const tidy = memoryId.replace(/-/g, '');
  return `M-${tidy.slice(0, 6)}`;
}

/** Convert 1..9 to a superscript glyph; fall back to "[N]" for ≥ 10. */
function superscript(n: number): string {
  if (n < 1) return '';
  const map: Record<number, string> = {
    1: '¹',
    2: '²',
    3: '³',
    4: '⁴',
    5: '⁵',
    6: '⁶',
    7: '⁷',
    8: '⁸',
    9: '⁹',
  };
  return map[n] ?? `[${n}]`;
}

export interface ChapterExportPdfProps {
  book: ChapterPdfBook;
  chapter: ChapterPdfChapter;
  revision: ChapterPdfRevision;
  memories: ChapterPdfMemoryLookup[];
  /** Optional fixed render time — defaults to now(). Tests inject. */
  generatedAt?: Date;
}

const FOOTER_TEXT =
  'Generated by Pantheon Autobiographer OS — provenance preserved';

/**
 * Split a body string into paragraphs the way the citations payload
 * expects: double-newline separates paragraphs, single newlines stay
 * with the paragraph. Empty paragraphs are dropped.
 */
export function splitParagraphs(body: string): string[] {
  if (!body) return [];
  return body
    .split(/\n\s*\n/g)
    .map((p) => p.replace(/\s+$/g, ''))
    .filter((p) => p.trim().length > 0);
}

export function ChapterExportPdf({
  book,
  chapter,
  revision,
  memories,
  generatedAt,
}: ChapterExportPdfProps): React.ReactElement {
  const paragraphs = splitParagraphs(revision.bodyText);
  const memoryById = new Map<string, ChapterPdfMemoryLookup>();
  for (const m of memories) memoryById.set(m.id, m);

  const citationsByParagraph = new Map<number, RevisionCitation>();
  for (const c of revision.citations) {
    citationsByParagraph.set(c.paragraphIndex, c);
  }

  // Build a deduped footnote list — every cited memory appears once.
  const footnoteOrder: string[] = [];
  const footnoteIndex = new Map<string, number>();
  for (const c of revision.citations) {
    for (const memoryId of c.memoryIds) {
      if (!footnoteIndex.has(memoryId)) {
        footnoteOrder.push(memoryId);
        footnoteIndex.set(memoryId, footnoteOrder.length);
      }
    }
  }

  const chapterTitle = chapter.title ?? 'Untitled chapter';
  const positionLabel = `Ch ${String(chapter.position + 1).padStart(2, '0')}`;

  return (
    <Document>
      <Page size="LETTER" style={PdfPageStyles.page}>
        <PdfHeader
          title={chapterTitle}
          subtitle={`${book.title} — ${positionLabel}`}
          projectName="Pantheon Autobiographer OS"
          generatedAt={generatedAt}
        />

        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 4 }}>
          <Text style={styles.meta}>
            Revision v{revision.version} by {revision.author === 'coach' ? 'coach' : 'user'}
            {'  ·  '}
            {revision.wordCount.toLocaleString()} words
            {'  ·  '}
            {paragraphs.length} {paragraphs.length === 1 ? 'paragraph' : 'paragraphs'}
          </Text>
          <Text style={styles.statusBadge}>
            {CHAPTER_STATUS_LABELS[chapter.status]}
          </Text>
        </View>

        {chapter.summary ? (
          <Text style={styles.summary}>{chapter.summary}</Text>
        ) : null}

        {paragraphs.length === 0 ? (
          <Text style={styles.empty}>
            This revision has no prose yet.
          </Text>
        ) : (
          paragraphs.map((p, i) => {
            const cite = citationsByParagraph.get(i);
            const markers = cite
              ? cite.memoryIds
                  .map((mid) => footnoteIndex.get(mid))
                  .filter((n): n is number => typeof n === 'number')
                  .map((n) => superscript(n))
                  .join('')
              : '';
            return (
              <Text key={`p-${i}`} style={styles.paragraph}>
                {p}
                {markers ? ' ' : ''}
                {markers}
              </Text>
            );
          })
        )}

        {footnoteOrder.length > 0 ? (
          <View wrap={false}>
            <Text style={styles.footnoteHeading}>Source memories</Text>
            {footnoteOrder.map((mid, i) => {
              const memory = memoryById.get(mid);
              const title = memory?.title ?? 'memory not available';
              const era = memory?.whenInLife ? ` (${memory.whenInLife})` : '';
              return (
                <Text key={`fn-${mid}`} style={styles.footnote}>
                  {superscript(i + 1)} from memory {shortMemoryId(mid)} ‘{title}’
                  {era}
                </Text>
              );
            })}
          </View>
        ) : null}

        <PdfFooter projectName={FOOTER_TEXT} />
      </Page>
    </Document>
  );
}
