import Link from 'next/link';
import { ArrowLeft, CalendarDays } from 'lucide-react';
import { redirect } from 'next/navigation';
import { getCurrentHealthUser } from '@/lib/agentic-os/health/session';
import {
  getActiveConsent,
  getCurrentMeditationPlan,
} from '@/lib/agentic-os/health/repo';
import { PlanCard } from '@/components/agentic-os/health/meditate/plan-card';
import { RegeneratePlanButton } from './regenerate-button';

export const dynamic = 'force-dynamic';

export default async function MeditationPlanPage() {
  const user = await getCurrentHealthUser();
  if (!user) redirect('/login');

  const mentalConsent = await getActiveConsent(
    user.userId,
    user.tenantId,
    'mental',
  );
  if (!mentalConsent?.granted) {
    redirect('/dashboard/os/health/meditate');
  }

  const plan = await getCurrentMeditationPlan(user.userId);

  return (
    <div className="max-w-3xl">
      <Link
        href="/dashboard/os/health/meditate"
        className="inline-flex items-center gap-1.5 text-sm text-text-secondary hover:text-white mb-4 transition"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to meditate
      </Link>

      <div className="flex items-center justify-between gap-3 mb-6">
        <div className="flex items-center gap-3">
          <CalendarDays className="w-6 h-6 text-accent" />
          <h1 className="text-2xl font-semibold text-white">Weekly plan</h1>
        </div>
        <RegeneratePlanButton hasPlan={!!plan} />
      </div>

      <PlanCard plan={plan} />

      <p className="text-[10px] text-text-secondary/70 mt-4 leading-relaxed">
        Plans are generated by deterministic rules over your recent mood,
        sleep, and stress signals. No LLM is involved in this phase. You
        can regenerate the plan any time — it will overwrite the current
        week’s plan.
      </p>
    </div>
  );
}
